### ISSUE TITLE
If .aws directory is empty the error is unhelpful

### ISSUE THREAD

**Issue by itamarst** [datawire/loom#15] opened 2017-04-27 16:34 UTC
When I start with `~.aws`-based option, I get the following mysterious error:

```
Exception in thread "main" com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
        at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:371)
        at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:337)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at io.datawire.loom.proto.aws.AwsProvider.newBlockingIamClient(AwsProvider.kt:118)
        at io.datawire.loom.proto.aws.AwsProvider.<init>(AwsProvider.kt:34)
        at io.datawire.loom.Loom.<init>(Loom.kt:34)
        at io.datawire.loom.RunnerKt.main(Runner.kt:16)
```

It might be better to say something like "We can't find any credentials in ~/.aws - either add them or use the environment-variable based mechanism." or something.

**Comment by plombardi89** [comment] 2017-04-27 16:36
Duplicate of #14

**Closed as completed by plombardi89** 2017-04-27 16:36 UTC
